CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, wallet_address varchar(42) UNIQUE NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), last_login_at timestamptz);
CREATE TABLE IF NOT EXISTS auth_nonces (wallet_address varchar(42) NOT NULL, nonce_hash varchar(128) NOT NULL, expires_at timestamptz NOT NULL, consumed_at timestamptz, PRIMARY KEY(wallet_address, nonce_hash));
CREATE TABLE IF NOT EXISTS sales_index (sale_id varchar(66) PRIMARY KEY, seller varchar(42) NOT NULL, buyer varchar(42) NOT NULL, asset_contract varchar(42) NOT NULL, token_id numeric(78,0) NOT NULL, asset_amount numeric(78,0) NOT NULL, payment_chain_key bigint NOT NULL, payment_chain_id bigint NOT NULL, payment_token varchar(42) NOT NULL, payment_recipient varchar(42) NOT NULL, payment_amount numeric(78,0) NOT NULL, source_start_block bigint NOT NULL, source_end_block bigint NOT NULL, status varchar(24) NOT NULL, creation_tx_hash varchar(66), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS payment_attempts (id uuid PRIMARY KEY, sale_id varchar(66) NOT NULL REFERENCES sales_index(sale_id), source_tx_hash varchar(66) UNIQUE NOT NULL, source_block bigint, payer varchar(42), recipient varchar(42), token varchar(42), amount_raw numeric(78,0), status varchar(32) NOT NULL, detected_at timestamptz NOT NULL DEFAULT now(), last_error_code varchar(64), last_error_message text);
CREATE TABLE IF NOT EXISTS proof_jobs (id uuid PRIMARY KEY, payment_attempt_id uuid UNIQUE NOT NULL REFERENCES payment_attempts(id), chain_key bigint NOT NULL, block_height bigint, status varchar(32) NOT NULL, attempt_count int NOT NULL DEFAULT 0, next_retry_at timestamptz, creditcoin_tx_hash varchar(66), query_id varchar(66), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS chain_cursors (chain varchar(32) NOT NULL, contract varchar(42) NOT NULL, last_scanned_block bigint NOT NULL, last_finalized_block bigint NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(chain, contract));
CREATE TABLE IF NOT EXISTS audit_events (id uuid PRIMARY KEY, event_type varchar(64) NOT NULL, sale_id varchar(66), payment_attempt_id uuid, details jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS proof_jobs_due_idx ON proof_jobs(status, next_retry_at);
CREATE INDEX IF NOT EXISTS audit_events_sale_idx ON audit_events(sale_id, created_at);
